### ISSUE TITLE
Cannot See Gauge under Widgets

### ISSUE THREAD

**Issue by yaseentayob** [jack-valko/Zabbix-Dashboard-Gauge#10]
I have installed the application successfully  but do not see the widget under my dashboards.  Running Zabbix V 6.0.3

# ./gauge-installer
******************************************************************
* ZABBIX DASHBOARD GAUGE INSTALLER                               *
*                                                                *
* This script runs some pre-flight tests to determine if you can *
* safely patch before updating zabbix-web with the gauge widget. *
******************************************************************

Verifying installed binaries ... OK

Zabbix Web Docroot [/usr/share/zabbix]:
Verifying zabbix release ... 6.0.3
Looking for the patch ... OK
Backing up /usr/share/zabbix to /tmp/zabbix-web-6.0.3-1651743169.tar ... OK

The script will now test the patch to be installed.
Press [ENTER] to begin or CTRL-C to exit:

Testing patch install
checking file app/controllers/CControllerWidgetGaugeView.php
checking file app/views/monitoring.widget.gauge.view.php
checking file assets/styles/blue-theme.css
checking file assets/styles/dark-theme.css
checking file include/classes/mvc/CRouter.php
checking file include/classes/widgets/CWidgetConfig.php
checking file include/classes/widgets/forms/CWidgetFormGauge.php
checking file include/classes/widgets/views/widget.gauge.form.view.php
checking file include/defines.inc.php
Patch test completed successfully.

Press [ENTER] to install the patch, CTRL-C to exit:

Performing patch install
patching file app/controllers/CControllerWidgetGaugeView.php
patching file app/views/monitoring.widget.gauge.view.php
patching file assets/styles/blue-theme.css
patching file assets/styles/dark-theme.css
patching file include/classes/mvc/CRouter.php
patching file include/classes/widgets/CWidgetConfig.php
patching file include/classes/widgets/forms/CWidgetFormGauge.php
patching file include/classes/widgets/views/widget.gauge.form.view.php
patching file include/defines.inc.php
Patch install completed successfully.

Please refresh your browser before continuing.

**Comment by jack-valko** [comment]
Another thought: check your zabbix_server and http error logs.  Post any relevant errors in this thread. Thanks.

**Comment by yaseentayob** [comment]
Thanks for the feedback.  I have restarted the ZABBIX server after installation of the package.  I have checked and confirmed that we only using 1 docroot folder for ZABBIX.  

I have checked zabbix server log and HTTP error logs and there are no errors relating to the gauge.

My server is running on VMWare Esxi 7 host
CentOS Stream 8
Zabbix 6.0.3
Web Server NGINX

**Comment by yaseentayob** [comment]
Apologies Jack, there was another docroot folder.  I have setup the package again and its working 100%.  Sorry about this

**Comment by jack-valko** [comment]
Great news!  Glad you found the problem, I'll close this ticket.
