### ISSUE TITLE
gauge colors issue in firefox

### ISSUE THREAD

**Issue by eins** [jack-valko/Zabbix-Dashboard-Gauge#7]
Hey Jack I installed Zabbix-Dashboard-Gauge in zabbix 6.0.3 that I just compiled it. 
the plugin is working but I don't have the same colors for the Gauge like you posted in the pictures:

https://github.com/jack-valko/Zabbix-Dashboard-Gauge/blob/main/images/gauge-image-large.png
or 
https://github.com/jack-valko/Zabbix-Dashboard-Gauge/blob/main/images/gauge-image-large.png

is there any particular package that I need to install in my zabbix server in order to have the same colors that you upload for the interrupts (blue/yellow/red)

I'm uploading an image from my current first gauge:

![my current zabbixGauge](https://user-images.githubusercontent.com/5210927/161673935-959d2999-16de-4804-8d48-3c7d70abf153.png)

**Comment by jack-valko** [comment]
Hello and thanks for your report.  There's nothing else to install.  The colors you select are the system colors you've chosen to represent the trigger severities ('Info', 'Warning', 'Average', etc).

Can you post a screen capture of the 'edit widget' screen for one of these gauges?  It looks like there's a range overflow bug happening, and layers may not be drawing in the correct order.  Here's is my gauge and edit view.

<img width="257" alt="Screen Shot 2022-04-04 at 10 48 00 PM" src="https://user-images.githubusercontent.com/83570325/161687257-aeca1261-75e2-45a4-bfdc-b2a8e819d0d2.png">

<img width="680" alt="Screen Shot 2022-04-04 at 10 49 00 PM" src="https://user-images.githubusercontent.com/83570325/161687290-ad24d375-29b3-4960-9fc6-5944096177f4.png">

Any warnings or errors during install?

**Comment by eins** [comment]
I didn't have errors during the install 
I ran the reverse just to be sure this is the output:

```
bash gauge-installer -r
******************************************************************
* ZABBIX DASHBOARD GAUGE INSTALLER                               *
*                                                                *
* This script runs some pre-flight tests to determine if you can *
* safely patch before updating zabbix-web with the gauge widget. *
******************************************************************

Verifying installed binaries ... OK

Zabbix Web Docroot [/usr/share/zabbix]: /websites/zabbix/www
Verifying zabbix release ... 6.0.1
Looking for the patch ... OK

The script will now test the patch to be uninstalled.
Press [ENTER] to begin or CTRL-C to exit:

Testing patch uninstall
checking file app/controllers/CControllerWidgetGaugeView.php
checking file app/views/monitoring.widget.gauge.view.php
checking file assets/styles/blue-theme.css
checking file assets/styles/dark-theme.css
checking file include/classes/mvc/CRouter.php
checking file include/classes/widgets/CWidgetConfig.php
checking file include/classes/widgets/forms/CWidgetFormGauge.php
checking file include/classes/widgets/views/widget.gauge.form.view.php
checking file include/defines.inc.php
Patch test completed successfully.


Please refresh your browser before continuing.
```

after this the three gauge that I had are gone.
I re install it

```
bash gauge-installer
******************************************************************
* ZABBIX DASHBOARD GAUGE INSTALLER                               *
*                                                                *
* This script runs some pre-flight tests to determine if you can *
* safely patch before updating zabbix-web with the gauge widget. *
******************************************************************

Verifying installed binaries ... OK

Zabbix Web Docroot [/usr/share/zabbix]:  /websites/zabbix/www
Verifying zabbix release ... 6.0.1
Looking for the patch ... OK
Backing up /websites/zabbix/www to /tmp/zabbix-web-6.0.1-1649162069.tar ... OK

The script will now test the patch to be installed.
Press [ENTER] to begin or CTRL-C to exit:

Testing patch install
checking file app/controllers/CControllerWidgetGaugeView.php
checking file app/views/monitoring.widget.gauge.view.php
checking file assets/styles/blue-theme.css
checking file assets/styles/dark-theme.css
checking file include/classes/mvc/CRouter.php
checking file include/classes/widgets/CWidgetConfig.php
checking file include/classes/widgets/forms/CWidgetFormGauge.php
checking file include/classes/widgets/views/widget.gauge.form.view.php
checking file include/defines.inc.php
Patch test completed successfully.

Press [ENTER] to install the patch, CTRL-C to exit:

Performing patch install
patching file app/controllers/CControllerWidgetGaugeView.php
patching file app/views/monitoring.widget.gauge.view.php
patching file assets/styles/blue-theme.css
patching file assets/styles/dark-theme.css
patching file include/classes/mvc/CRouter.php
patching file include/classes/widgets/CWidgetConfig.php
patching file include/classes/widgets/forms/CWidgetFormGauge.php
patching file include/classes/widgets/views/widget.gauge.form.view.php
patching file include/defines.inc.php
Patch install completed successfully.

Please refresh your browser before continuing.
```

the only weird thing there is that is said 6.0.1 but I'm running zabbix 6.0.3

```
zabbix_server --version
zabbix_server (Zabbix) 6.0.3
Revision 506e2b51e2 4 April 2022, compilation time: Apr  4 2022 23:07:20

Copyright (C) 2022 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 1.1.1f  31 Mar 2020
Running with OpenSSL 1.1.1f  31 Mar 2020
```

this are the edit widget screenshots

![editZabbixGauge02](https://user-images.githubusercontent.com/5210927/161755431-fbde1d8a-70bb-40b1-ad68-73c52d9f5f27.png)

![editZabbixGauge01](https://user-images.githubusercontent.com/5210927/161755434-741313f2-8036-4362-9a21-60fa33754e6e.png)

I still have the same colors in the gauge. something is off but I don't know what is it yet.

for the two edit widget option I have the same color:

![zabbixGaugeColorNotChanged](https://user-images.githubusercontent.com/5210927/161755696-944a68de-edbf-4197-8f81-a75a117e9047.png)

**Comment by jack-valko** [comment]
Run this command:
```grep 'ZABBIX_VERSION' /websites/zabbix/www/include/defines.inc.php```

Let me know which version is returned.  It looks like you've installed from sources, correct?  Does the gauge look 'normal' when the 'blue' theme is used?

Thank you!

**Comment by eins** [comment]
Jack I installed from source. 
I ran the ui cp again and I then I ran the ripgrep command

```
rg 'ZABBIX_VERSION' /websites/zabbix/www/include/defines.inc.php
21:define('ZABBIX_VERSION',             '6.0.3');
```

in order to avoid any other confusion I re ran the gauge-installer again

```
./gauge-installer
******************************************************************
* ZABBIX DASHBOARD GAUGE INSTALLER                               *
*                                                                *
* This script runs some pre-flight tests to determine if you can *
* safely patch before updating zabbix-web with the gauge widget. *
******************************************************************

Verifying installed binaries ... OK

Zabbix Web Docroot [/usr/share/zabbix]: /websites/zabbix/www
Verifying zabbix release ... 6.0.3
Looking for the patch ... OK
Backing up /websites/zabbix/www to /tmp/zabbix-web-6.0.3-1649178417.tar ... OK

The script will now test the patch to be installed.
Press [ENTER] to begin or CTRL-C to exit:

Testing patch install
checking file app/controllers/CControllerWidgetGaugeView.php
checking file app/views/monitoring.widget.gauge.view.php
checking file assets/styles/blue-theme.css
checking file assets/styles/dark-theme.css
checking file include/classes/mvc/CRouter.php
checking file include/classes/widgets/CWidgetConfig.php
checking file include/classes/widgets/forms/CWidgetFormGauge.php
checking file include/classes/widgets/views/widget.gauge.form.view.php
checking file include/defines.inc.php
Patch test completed successfully.

Press [ENTER] to install the patch, CTRL-C to exit:

Performing patch install
patching file app/controllers/CControllerWidgetGaugeView.php
patching file app/views/monitoring.widget.gauge.view.php
patching file assets/styles/blue-theme.css
patching file assets/styles/dark-theme.css
patching file include/classes/mvc/CRouter.php
patching file include/classes/widgets/CWidgetConfig.php
patching file include/classes/widgets/forms/CWidgetFormGauge.php
patching file include/classes/widgets/views/widget.gauge.form.view.php
patching file include/defines.inc.php
Patch install completed successfully.

Please refresh your browser before continuing.
```

**Comment by jack-valko** [comment]
What do these gauges look like with the 'blue' theme turned on?  I'm trying to figure out if this is a problem with the drawing logic or the css.  What browser are you using?  Thanks.

**Comment by eins** [comment]
Jack I'm using  Firefox 98.0 (64-bit) without any Extensions or addons

I changed zabbix theme to Blue and re login. the dashboard still have a dark background and the gauge are the same. 
all with the same colors and the dark gray background.

**Comment by eins** [comment]
Jack I installed brave browser and I have an update . the colors now looks better but with blue or dark UI options 
the background still black.

![gauge-braveBrowser01](https://user-images.githubusercontent.com/5210927/161819150-c00d7582-8381-43f3-80f0-1e8ccce61066.png)

**Comment by eins** [comment]
gauge looks way better in brave browser Version 1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit)

![gauge-braveBrowser02](https://user-images.githubusercontent.com/5210927/161820652-5c492169-cb46-40c4-b307-aba890d4bd3a.png)

**Comment by jack-valko** [comment]
Yeah you read my mind here.  I have tested this in chrome only.  The firefox output looks so bizarre I need to get a repro on it to understand what is going on.

**Comment by jack-valko** [comment]
Can you post a full page dashboard screen cap in blue mode?

**Comment by eins** [comment]
Jack this is a screenshot with blue mode in brave browser

![zabbixFullPic01](https://user-images.githubusercontent.com/5210927/161835792-70f440b8-849d-4cae-8b7f-3ce2915cb263.png)

**Comment by jack-valko** [comment]
That looks like dark mode.  In the UI navigate to Administration -> General -> GUI.  Default theme should show 'Dark'.  If it shows 'Blue' there could be an application level CSS issue with your zabbix-web install.

**Comment by eins** [comment]
yes Jack it could be a css issue level because when I switched to blue the login part was the only that changed to the bright invasive white background, after the login the dashboard had the dark background .

**Comment by jack-valko** [comment]
There appear to be two issues with firefox.  The first issue is the shaded areas do not appear as arcs, but as full circles.  The second issue is the "majorticks" and "minorticks" are not drawing.

For the first issue, here is the offending command that firefox renders as a shaded circle instead of an arc:
```<circle cx="75" cy="75" r="53" fill="none" stroke="#FFC859" stroke-opacity="80%" stroke-width="9" stroke-dasharray="calc(2*22/7*53*500/1000*240/360), calc(2*22/7*53)"></circle>```
Firefox will not execute the calc() inside stroke-dasharray. This bug was opened 6 years ago. https://bugzilla.mozilla.org/show_bug.cgi?id=1258270

The second issue is firefox not identifying the CSS for stroke color for the minor and major tick marks.  I have a fix for this in dev and will post a new 6.0.3 patch shortly.

**Comment by eins** [comment]
thanks for the last reply Jack.
I can wait to test the patch.

**Comment by jack-valko** [comment]
Just pushed it.  The gauges look better now, but shaded region support will require a rethink of how those graphic elements are drawn.

**Comment by eins** [comment]
I pull the changes and re install it with ./gauge-installer

first picture is from firefox
![zabbixGauge03_with_patch](https://user-images.githubusercontent.com/5210927/161889626-2aaa1bc6-cf74-495c-87fc-9a79ebf289d0.png)

second picture is from brave browser
![zabbixGauge04_with_patch](https://user-images.githubusercontent.com/5210927/161889773-2a9e7cfd-f67a-44c3-afef-7fbd8dfa5854.png)

**Comment by jack-valko** [comment]
I think this bug is fixed now.  Please grab the latest version of the patch to confirm.  Thank you.

**Comment by eins** [comment]
Jack it is working now. thanks!

this screenshot is from firefox
![zabbixGauge05_with_patch](https://user-images.githubusercontent.com/5210927/161893537-4b08845a-9d26-496b-86c4-e35e77bd5b29.png)

**Comment by jack-valko** [comment]
Thank you for testing this!
